import { expect } from "chai";
import hre, { ethers } from "hardhat";
// @ts-ignore - circomlibjs ships its own types loosely
import { poseidonContract, buildPoseidon } from "circomlibjs";

const LEVELS = 20;
const DENOMINATION = ethers.parseEther("0.1");

describe("NullifyPool", () => {
  async function deploy() {
    const [deployer, user] = await ethers.getSigners();

    // deploy the Poseidon(2) hasher from circomlibjs-generated bytecode
    const abi = poseidonContract.generateABI(2);
    const bytecode = poseidonContract.createCode(2);
    const Hasher = new ethers.ContractFactory(abi, bytecode, deployer);
    const hasher = await Hasher.deploy();
    await hasher.waitForDeployment();

    const Pool = await ethers.getContractFactory("NullifyPool");
    const pool = await Pool.deploy(LEVELS, await hasher.getAddress(), DENOMINATION);
    await pool.waitForDeployment();

    return { pool, user };
  }

  it("accepts a deposit of the correct denomination and advances the root", async () => {
    const { pool, user } = await deploy();
    const poseidon = await buildPoseidon();

    const nullifier = 12345n;
    const secret = 67890n;
    const commitment =
      "0x" + poseidon.F.toString(poseidon([nullifier, secret]), 16).padStart(64, "0");

    const before = await pool.getLastRoot();
    await expect(pool.connect(user).deposit(commitment, { value: DENOMINATION }))
      .to.emit(pool, "Deposit");
    const after = await pool.getLastRoot();

    expect(after).to.not.equal(before);
    expect(await pool.isKnownRoot(after)).to.equal(true);
  });

  it("rejects the wrong denomination", async () => {
    const { pool, user } = await deploy();
    await expect(
      pool.connect(user).deposit("0x" + "11".repeat(32), { value: ethers.parseEther("0.05") }),
    ).to.be.revertedWith("wrong denomination");
  });
});
