// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

interface IHasher {
    function poseidon(bytes32[2] calldata input) external pure returns (bytes32);
}

/// @title MerkleTreeWithHistory
/// @notice Fixed-depth incremental Merkle tree with a rolling window of recent roots.
/// @dev Poseidon hashing is delegated to an IHasher generated by circomlibjs
///      (poseidonContract). This matches the in-circuit Poseidon so proofs verify.
contract MerkleTreeWithHistory {
    uint256 public constant FIELD_SIZE =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;
    uint256 public constant ZERO_VALUE =
        21663839004416932945382355908790599225266501822907911457504978515578255421292; // keccak256("nullify") % FIELD_SIZE

    IHasher public immutable hasher;
    uint32 public immutable levels;

    // current branch fillers + precomputed zero subtrees
    mapping(uint256 => bytes32) public filledSubtrees;
    mapping(uint256 => bytes32) public zeros;

    uint32 public currentRootIndex;
    uint32 public nextIndex;

    uint32 public constant ROOT_HISTORY_SIZE = 30;
    bytes32[ROOT_HISTORY_SIZE] public roots;

    constructor(uint32 _levels, IHasher _hasher) {
        require(_levels > 0 && _levels < 33, "levels out of range");
        levels = _levels;
        hasher = _hasher;

        bytes32 current = bytes32(ZERO_VALUE);
        for (uint32 i = 0; i < _levels; i++) {
            zeros[i] = current;
            filledSubtrees[i] = current;
            current = _hash(current, current);
        }
        roots[0] = current;
    }

    function _hash(bytes32 left, bytes32 right) internal view returns (bytes32) {
        require(uint256(left) < FIELD_SIZE && uint256(right) < FIELD_SIZE, "out of field");
        return hasher.poseidon([left, right]);
    }

    function _insert(bytes32 leaf) internal returns (uint32 index) {
        uint32 _nextIndex = nextIndex;
        require(uint256(_nextIndex) != 2 ** uint256(levels), "tree is full");

        uint32 currentIndex = _nextIndex;
        bytes32 currentHash = leaf;
        bytes32 left;
        bytes32 right;

        for (uint32 i = 0; i < levels; i++) {
            if (currentIndex % 2 == 0) {
                left = currentHash;
                right = zeros[i];
                filledSubtrees[i] = currentHash;
            } else {
                left = filledSubtrees[i];
                right = currentHash;
            }
            currentHash = _hash(left, right);
            currentIndex /= 2;
        }

        uint32 newRootIndex = (currentRootIndex + 1) % ROOT_HISTORY_SIZE;
        currentRootIndex = newRootIndex;
        roots[newRootIndex] = currentHash;
        nextIndex = _nextIndex + 1;
        return _nextIndex;
    }

    function isKnownRoot(bytes32 root) public view virtual returns (bool) {
        if (root == bytes32(0)) return false;
        uint32 i = currentRootIndex;
        do {
            if (root == roots[i]) return true;
            i = i == 0 ? ROOT_HISTORY_SIZE - 1 : i - 1;
        } while (i != currentRootIndex);
        return false;
    }

    function getLastRoot() public view returns (bytes32) {
        return roots[currentRootIndex];
    }
}
